language: java

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

script: 
  - mkdir temp
  - ./updatenC.sh
  - mkdir osb/cerebellum
  - mkdir osb/cerebellum/cerebellar_granule_cell
  - git clone https://github.com/OpenSourceBrain/GranuleCell.git osb/cerebellum/cerebellar_granule_cell/GranuleCell
  - ant testcore

